#!/bin/sh
set -e

case "$1" in
    remove)
	# delete seeks daemon user
	# test if exists just to don't generate error
	if getent passwd seeks > /dev/null ; then
	 echo "Deleting seeks user"
	 deluser --quiet seeks > /dev/null || true
	fi
    ;;
    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
